x-db-env: &x-db-env
  POSTGRES_DB: "chat"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "user"
  PGDATA: "/var/lib/postgresql/data"

services:
  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    environment:
      <<: *x-db-env
    volumes:
      - chat_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    mem_limit: 256Mb
    cpus: 0.25

volumes:
  chat_data:
